const MSG_CONTENT_TYPE = {
  TEXT: 'text',
  IMAGE: 'image'
};

const COMMAND_TYPE = {
  SEND_P2P_MSG: 'sendP2PMsg',
  SEND_GROUP_MSG: 'sendGroupMsg'
};

const MSG_TYPE = {
  SERVER_REC_CONFIRM: 'SERVER_REC_CONFIRM',
  REC_P2P_MSG: 'REC_P2P_MSG',
  REC_GROUP_MSG: 'REC_GROUP_MSG',
  EXCEPTION: 'EXCEPTION',
  SYNC_REQ: 'SYNC_REQ',
  PLATFORM_INFO: 'PLATFORM_INFO',
  HOME_PAGE: 'HOME_PAGE',
  CONTANCT_INFO_UPDATE: 'CONTANCT_INFO_UPDATE',
  CONTANCT_INFO_DELETE: 'CONTANCT_INFO_DELETE',
  GROUP_INFO_UPDATE: 'GROUP_INFO_UPDATE',
  GROUP_INFO_DELETE: 'GROUP_INFO_DELETE'
};

const ITEM_TYPE = {
  GROUP: 'group',
  USER: 'user'
};

const CHANGE_EVENT = {
  CHANGE: 'CHANGE',
  ADD: 'ADD',
  UPDATE: 'UPDATE'
};

module.exports = {
  MSG_CONTENT_TYPE: MSG_CONTENT_TYPE,
  COMMAND_TYPE: COMMAND_TYPE,
  MSG_TYPE: MSG_TYPE,
  ITEM_TYPE: ITEM_TYPE,
  CHANGE_EVENT: CHANGE_EVENT
};
