const MSG_CONTENT_TYPE = {
  TEXT: 'text',
  IMAGE: 'image',
  NAMECARD:'namecard',
  BIZINFO:'bizinfo',
  NULL:'null'
};

const COMMAND_TYPE = {
  SEND_P2P_MSG: 'sendP2PMsg',
  SEND_GROUP_MSG: 'sendGroupMsg',
  SYNC_REQ:'SYNC_REQ'
};

const MSG_TYPE = {
  SERVER_REC_CONFIRM: 'SERVER_REC_CONFIRM',
  REC_P2P_MSG: 'REC_P2P_MSG',
  REC_GROUP_MSG: 'REC_GROUP_MSG',
  EXCEPTION: 'EXCEPTION',
  SYNC_REQ: 'SYNC_REQ',
  PLATFORM_INFO: 'PLATFORM_INFO',
  HOME_PAGE: 'HOME_PAGE',
  CONTANCT_INFO_UPDATE: 'CONTANCT_INFO_UPDATE',
  CONTANCT_INFO_DELETE: 'CONTANCT_INFO_DELETE',
  GROUP_INFO_UPDATE: 'GROUP_INFO_UPDATE',
  GROUP_INFO_DELETE: 'GROUP_INFO_DELETE',
  GROUP_JOIN_INVITE:'GROUP_JOIN_INVITE',
  SYNC_RES: 'SYNC_RES',
  FORCE_LOGOUT:'FORCE_LOGOUT',
  CERTIFICATION:'CERTIFICATION',
  USER_FROZEN:'USER_FROZEN',
  USER_DELETE:'USER_DELETE',
  FRIEND_INVITE:'FRIEND_INVITE',
  FRIEND_PROMISE:'FRIEND_PROMISE'
};

const SESSION_TYPE = {
  GROUP: 'group',
  USER: 'user',
  INVITE:'invite',
  INVITED:'invited',
  PLATFORMINFO:'platforminfo',
  NEWFRIEND:'newfriend'
};

module.exports = {
  MSG_CONTENT_TYPE: MSG_CONTENT_TYPE,
  COMMAND_TYPE: COMMAND_TYPE,
  MSG_TYPE: MSG_TYPE,
  SESSION_TYPE: SESSION_TYPE,
};
