const MSG_CONTENT_TYPE = {
  TEXT: 'text',
  IMAGE: 'image',
  NAMECARD:'namecard',
  BIZINFO:'bizinfo',
};

const COMMAND_TYPE = {
  SEND_P2P_MSG: 'sendP2PMsg',
  SEND_GROUP_MSG: 'sendGroupMsg',
  SYNC_REQ: 'SYNC_REQ',
  KPI_APP: 'kpiApp'
};

const KPI_TYPE = {
  PAGE: 'PAGE',
  SHARE: 'SHARE',
  PUSH: 'PUSH'
};

const MSG_TYPE = {
  SERVER_REC_CONFIRM: 'SERVER_REC_CONFIRM',
  REC_P2P_MSG: 'REC_P2P_MSG',
  REC_GROUP_MSG: 'REC_GROUP_MSG',
  EXCEPTION: 'EXCEPTION',
  SYNC_REQ: 'SYNC_REQ',
  PLATFORM_INFO: 'PLATFORM_INFO',
  HOME_PAGE: 'HOME_PAGE',
  CONTANCT_INFO_UPDATE: 'CONTANCT_INFO_UPDATE',
  CONTANCT_INFO_DELETE: 'CONTANCT_INFO_DELETE',
  GROUP_INFO_UPDATE: 'GROUP_INFO_UPDATE',
  GROUP_INFO_DELETE: 'GROUP_INFO_DELETE',
  GROUP_JOIN_INVITE:'GROUP_JOIN_INVITE',
  SYNC_RES: 'SYNC_RES',
  FORCE_LOGOUT:'FORCE_LOGOUT',
  CONTANCT_INFO_CERTIFY:'CONTANCT_INFO_CERTIFY',
  CONTANCT_INFO_UNCERTIFY:'CONTANCT_INFO_UNCERTIFY',
  CONTANCT_INFO_FREEZE:'CONTANCT_INFO_FREEZE',
  ORG_INFO_UPDATE:'ORG_INFO_UPDATE'
};

const SESSION_TYPE = {
  GROUP: 'group',
  USER: 'user',
  INVITE:'invite',
  INVITED:'invited',
  PLATFORMINFO:'platforminfo',
};

module.exports = {
  MSG_CONTENT_TYPE: MSG_CONTENT_TYPE,
  COMMAND_TYPE: COMMAND_TYPE,
  MSG_TYPE: MSG_TYPE,
  KPI_TYPE: KPI_TYPE,
  SESSION_TYPE: SESSION_TYPE,
};
