
module.exports = {

    SERVER_REC_CONFIRM:'SERVER_REC_CONFIRM',
    REC_P2P_MSG:'REC_P2P_MSG',
    REC_GROUP_MSG:'REC_GROUP_MSG',
    EXCEPTION:'EXCEPTION',
    SYNC_REQ:'SYNC_REQ',
    PLATFORM_INFO:'platform_info',
    HOME_PAGE:'HOME_PAGE',
    CONTANCT_INFO_UPDATE:'CONTANCT_INFO_UPDATE',
    CONTANCT_INFO_DELETE:'CONTANCT_INFO_DELETE',
    GROUP_INFO_UPDATE:'GROUP_INFO_UPDATE',
    GROUP_INFO_DELETE:'GROUP_INFO_DELETE'

}